package: navigation_array
version: '2.0.1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/navigation_array
info: 'FOR Navigation Array'

requires:
    redaxo: '^5.15.0'
    php:
        version: '>=8.1'    
