package: navigation_array
version: '5.3.1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/navigation_array
info: 'REDAXO AddOn:Navigation Array'

requires:
    redaxo: '^5.15.0'
    php:
        version: '>=8.1'    
