# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: navigation_array
version: '1.1.0-beta'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/navigation_array
info: 'FOR Navigation Array'

requires:
    redaxo: '^5.8.0'
    php:
        version: '^7.1'    
