# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: navigation_array
version: '1.0.1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/klxm
info: 'FOR Navigation Array'

requires:
    redaxo: '>=5.8.0'
    
